### ISSUE TITLE
differential_drive uses wrong indexes for motors

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#26]
encoded_motors comments says that the indexes go from 1 - 4, but differential_drive uses indexes 0 and 1

**Comment by fgrossman** [comment]
Defaults also uses the wrong indexes assuming they are base 1 indexes as in the comments/docs are correct.

**Comment by Kreeevin** [comment]
Yea they were originally base zero indexed but I changed it so that motors 3 and 4 would correspond to indexes 3 and 4. Just made that change, will be fixed in the next version
