### ISSUE TITLE
Endoded_motor reset_encoder_position does not seem to be working

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#36]
The code below the number of ticks stays the same for both printouts

```
from XRPLib.encoded_motor import EncodedMotor
import time

motor1 = EncodedMotor.get_default_encoded_motor(1)


motor1.set_speed(60)
time.sleep(2)
motor1.set_speed()
print(motor1.get_position_ticks())
motor1.reset_encoder_position()
print(motor1.get_position_ticks())
```

**Comment by Kreeevin** [comment]
Same issue as #37 and therefore #31. There's a delay in when the update actually goes through:
![image](https://github.com/Open-STEM/XRP_MicroPython/assets/67293695/1699f754-7094-48cd-ade4-91f24bfdabf7)
![image](https://github.com/Open-STEM/XRP_MicroPython/assets/67293695/b824e87f-ab41-4633-8c8b-b091a09ea6e7)

**Comment by Kreeevin** [comment]
see comment on #31, solved for now
