### ISSUE TITLE
In webserver if a added button has a space in it, it does not work

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#38]
I created a button called LED on

When I pushed the button it said
Running LED
Exception in LED

If I shorten it to just LED as the button name, then it work fine.

**Comment by Kreeevin** [comment]
yup, this is a known issue, just haven't gotten around to fixing it, will push a fix later today

**Comment by Kreeevin** [comment]
just pushed a fix for this, will be part of the next version release
