### ISSUE TITLE
4wd? 

### ISSUE THREAD

**Issue by samuk** [Open-STEM/XRP_MicroPython#53]
I'm planning to do a 4wd not with my XRP board.

Is 4wd on your roadmap?

**Comment by Kreeevin** [comment]
4WD is not a default behavior of the XRP, so you'll have to construct a couple objects of your own, but it is definitely supported by the XRP in it's current state. You'll have to construct motor groups with your left and right motors, and then make a DifferentialDrive drivetrain object with them, but that is all pretty simple to do.

**Comment by samuk** [comment]
Great, Mecanum can be a project for later.
