### ISSUE TITLE
Add I2C functions to the library

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#7]

**Comment by Kreeevin** [comment]
Micropython already supports I2C communication without the need for our library to encapsulate it. [You can find the documentation for that here](https://docs.micropython.org/en/latest/library/machine.I2C.html)

**Comment by fgrossman** [comment]
True, my thought had to do with the fact that our Qwiic connector shares the I2C interface with the IMU. I didn't know if we maybe wanted to give a couple of functions in the library so that we don't suddenly loose control of the IMU
